### ISSUE TITLE
( BUG ) It won't work at blooket anymore 

### ISSUE THREAD

**Issue by Nobody-720** [GooseterV/GoogleTrans-Button#1]
( **It won't work even I use console & bookmark** )

**Comment by Nobody-720** [comment]
**Last Time That Webstie Can Be Used But For Now It Can't **( _Like Blooket_ )

**Comment by Nobody-720** [comment]
Oh ;=;

It won't work on blooket cause **they patched them already ** ;=;

**Comment by Nobody-720** [comment]
**While for other website is still work as normals**

**Comment by GooseterV** [comment]
If you check out what i said, it may not work on some websites due to CSP policies. A simple fix for this would be to paste the raw code into console directly.

**Comment by GooseterV** [comment]
@Nobody-720  try pasting code directly into the console instead of the `fetch` link.

**Comment by Nobody-720** [comment]
@GooseterV  Ok [ **it works as usually TQ** ]

**Comment by GooseterV** [comment]
Good.
